server:
  port: 8090

spring:
  data:
    mongodb:
      host: 101.37.172.74
      port: 27017
      username: jbank
      password: '123456'
      database: jbank

logging:
  file:
    path: /service/log/jbank-helper
    name: jbank-helper.log
    max-size: 10MB
    max-history: 7
